#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# To prevent bash from freezing on Ctr+S
stty -ixon

# Sourcing z.sh for better 'cd' (Refer https://github.com/rupa/z/blob/master/z.sh)
source ~/z.sh

unsetopt CORRECT                      # Disable autocorrect guesses. Happens when typing a wrong
                                      # command that may look like an existing one.

# fzf installation
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Interactive cd using fzf (https://github.com/changyuheng/zsh-interactive-cd)
source ~/zsh-interactive-cd/zsh-interactive-cd.plugin.zsh
